#!/bin/bash

[ -f $GIT_DIR/MERGE_MSG ] && exit 0

branch=`git rev-parse --abbrev-ref HEAD`
ticket=`echo $branch | egrep -o DEV-[0-9]+`

[ -z $ticket ] && exit 0

msg=`cat $1`

if ! [[ "$msg" =~ ^\[$ticket\] ]]
then
    echo -n "[$ticket] $msg" > $1
fi
